<a href="https://colab.research.google.com/github/ritu456286/Machine-Learning/blob/main/Forward_Propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **FORWARD PROPAGATION**

---



Here, we randomly select values of weights and biases for hidden and output layers, and reach to the conclusion by applying sigmoid as the Activation Function




In [ ]:
import numpy as np
import pandas as pd

X = np.array([[0,0], [0,1], [1, 0], [1,1]])
y = np.array([0,0,0,1]).reshape(4,1)
X.shape, y.shape

((4, 2), (4, 1))

In [ ]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

## With no hidden layers

In [ ]:
weights = 2 * np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[0.81964155],
        [0.09720538]]),
 array([0.07371931]))

In [ ]:
z = np.dot(X, weights) + bias
output = sigmoid(z)
output

array([[3.72007598e-44],
       [1.38879439e-11],
       [1.38879439e-11],
       [1.00000000e+00]])

## With one hidden layer

In [ ]:
num_neurons_hidden = 3
num_neurons_output = 1
weights_hidden = 2 * np.random.random((2, num_neurons_hidden)) - 1
bias_hidden = 2 * np.random.random((1, num_neurons_hidden)) - 1
weights_output = 2 * np.random.random((num_neurons_hidden, num_neurons_output)) - 1
bias_output = 2 * np.random.random((1, num_neurons_output)) - 1

In [ ]:
output_hidden = sigmoid(np.dot(X, weights_hidden) + bias_hidden)
output_hidden

array([[0.34409249, 0.71398592, 0.68712011],
       [0.24900952, 0.83103986, 0.83053972],
       [0.2870518 , 0.8296362 , 0.71512975],
       [0.20285606, 0.905616  , 0.84854025]])

In [ ]:
output = sigmoid(np.dot(output_hidden, weights_output) + bias_output)
output

array([[0.56618661],
       [0.55292306],
       [0.56441305],
       [0.55174702]])