# Eager Execution

In [4]:
import tensorflow as tf

In [21]:
var1 = tf.Variable(100)
print(var1.numpy())

100


In [12]:
var2 = tf.Variable([[100]])
var2

<tf.Variable 'Variable:0' shape=(1, 1) dtype=int32, numpy=array([[100]])>

In [15]:
sum = tf.add(var1, var2)
print(sum)

tf.Tensor([[200]], shape=(1, 1), dtype=int32)


In [22]:
var1.assign(1232)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=1232>

In [24]:
var1.numpy()

1232

In [25]:
var1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1232>

In [29]:
# var1.assign(12.32) 
## gives error: TypeError: Cannot convert 12.32 to EagerTensor of dtype int32

# this means, type of variable cannot be changed after initalising it with data of some type;

In [30]:
var1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1232>

In [32]:
var2

<tf.Variable 'Variable:0' shape=(1, 1) dtype=int32, numpy=array([[100]])>

In [34]:
var1 + var2

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[1332]])>

In [35]:
z = tf.add(var1, var2)
z

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[1332]])>

# Graph Execution

In [37]:
@tf.function
def add(x, y):
    return x + y
z = add(tf.Variable(20), tf.Variable(30))
z

<tf.Tensor: shape=(), dtype=int32, numpy=50>